### ISSUE TITLE
Unknown option: "--allow_remote_gui_rpc"

### ISSUE THREAD

**Issue by hemna** [BOINC/boinc-client-docker#73]
I wrote a docker-compose.yml file to stand up boinc and I get the following output.

```
waboring@hpvirt1:~/docker/boinc: $  docker-compose up
Starting boinc_boinc_1 ... done
Attaching to boinc_boinc_1
boinc_1  | Unknown option: "--allow_remote_gui_rpc"
boinc_1  | The command-line options for /usr/bin/boinc are intended for debugging.
boinc_1  | The recommended command-line interface is a separate program,'boinccmd'.
boinc_1  | Run boinccmd in the same directory as /usr/bin/boinc.
boinc_1  |
boinc_1  | Usage: /usr/bin/boinc [options]
boinc_1  |     --abort_jobs_on_exit           when client exits, abort and report jobs
boinc_1  |     --allow_remote_gui_rpc         allow remote GUI RPC connections
```

my docker-compose.yml file
```
waboring@hpvirt1:~/docker/boinc: $  cat docker-compose.yml
version: "3"
services:
  boinc:
    image: boinc/client
    volumes:
        - /mnt/nfs-export/docker/boinc:/var/lib/boinc
    environment:
        - BOINC_GUI_RPC_PASSWORD="123"
        - BOINC_CMD_LINE_OPTIONS="--allow_remote_gui_rpc"
    network_mode: "host"
    pid: "host"
```
