### ISSUE TITLE
Science United reports arm32v7 client out of date

### ISSUE THREAD

**Issue by captcarl13** [BOINC/boinc-client-docker#92]
![image](https://user-images.githubusercontent.com/867543/149632157-b1f497fc-4dc1-4b1a-a9dd-09451e70b3d1.png)

![image](https://user-images.githubusercontent.com/867543/149632175-5d3e4f37-8ad2-488c-8890-c9515dd489f9.png)

Running client using `docker-compose`. See file below:
```
version: '2'
services:
  boinc:
    image: boinc/client:arm32v7
    container_name: boinc
    restart: always
    network_mode: host
    pid: host
    volumes:
      - /opt/appdata/boinc:/var/lib/boinc
      - /etc/localtime:/etc/localtime:ro
    environment:
      - BOINC_GUI_RPC_PASSWORD=123
      - BOINC_CMD_LINE_OPTIONS=--allow_remote_gui_rpc
```
